name: Update Publications

on:
  workflow_dispatch:      # allow manual runs
  schedule:
    - cron: "0 3 * * *"   # every night at 3 AM UTC
  push:
    paths:
      - "paper_ids.txt"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate publication list
        run: python scripts/fetch_papers.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.md
          git commit -m "Update publications" || echo "No changes"
          git push
